### ISSUE TITLE
Czech reading span crashing occasionally

### ISSUE THREAD

**Issue by fisfisifs** [tmalsburg/py-span-task#14]
Hello, we are using the Czech py-span-task (reading span with words). Sometimes it crashes, approximately once in four runs with no clear regularity. I am attaching the console output showing the error reports. It seems to be connected to the Unicode BOM character but I can't tell much more.
The relevant part of the output starts on line 17:

trial: test 2
  presented: Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\lib-tk\Tkinter.py", line 1536,

[error Word Span.txt](https://github.com/tmalsburg/py-span-task/files/3067838/error.Word.Span.txt)

**Comment by tmalsburg** [comment]
Thanks for creating this issue.  Yes, this seems to be somehow related to the BOM character and the fact that you're running this on Windows.  However, I checked the relevant files (`target_words_czech.txt` and `sentences_czech.txt`) and they don't seem to contain BOM characters.  So where is the BOM coming from?  The problem also seems to be specific to Windows because it arises when the output is encoded in the DOS encoding CP852 for display in the console.  Interestingly, your system seems to use code supplied by PsychoPy2 to do the encoding instead of the cp852.py supplied with the Python runtime.

```
File "C:\Program Files (x86)\PsychoPy2\lib\encodings\cp852.py", line 12, in en
```

Is it possible that PsychoPy2 is somehow the culprit?

**Comment by fisfisifs** [comment]
Hm, thanks for the tip, the machines definitely have psychopy on them and maybe the python installation is somehow intertwined with it. I'll check and report what I found.

**Comment by tmalsburg** [comment]
Thank you!

**Comment by tmalsburg** [comment]
I'm going to close this issue for now.  Feel free to reopen if the problem persists.
